[2024-11-10T12:54:34.647+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T12:54:31.306253+00:00 [queued]>
[2024-11-10T12:54:34.653+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T12:54:31.306253+00:00 [queued]>
[2024-11-10T12:54:34.654+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-10T12:54:34.664+0000] {taskinstance.py:2217} INFO - Executing <Task(RabbitMQSensor): trip_stop_sensor> on 2024-11-10 12:54:31.306253+00:00
[2024-11-10T12:54:34.669+0000] {standard_task_runner.py:60} INFO - Started process 3806 to run task
[2024-11-10T12:54:34.671+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'analytics_pipeline', 'trip_stop_sensor', 'scheduled__2024-11-10T12:54:31.306253+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/analytics_pipeline.py', '--cfg-path', '/tmp/tmpa0bw0pxs']
[2024-11-10T12:54:34.673+0000] {standard_task_runner.py:88} INFO - Job 155: Subtask trip_stop_sensor
[2024-11-10T12:54:34.709+0000] {task_command.py:423} INFO - Running <TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T12:54:31.306253+00:00 [running]> on host 2a2d16a2b1e8
[2024-11-10T12:54:34.769+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='analytics_pipeline' AIRFLOW_CTX_TASK_ID='trip_stop_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T12:54:31.306253+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-10T12:54:31.306253+00:00'
[2024-11-10T12:54:34.781+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/sensors/rabbitmq.py", line 32, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/sensors/rabbitmq.py", line 37, in poke
    message = hook.pull(self.queue_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 123, in pull
    connection = self.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 48, in get_conn
    conn = self.get_connection(self.rabbitmq_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `RabbitMQ` isn't defined
[2024-11-10T12:54:34.784+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=analytics_pipeline, task_id=trip_stop_sensor, execution_date=20241110T125431, start_date=20241110T125434, end_date=20241110T125434
[2024-11-10T12:54:34.793+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 155 for task trip_stop_sensor (The conn_id `RabbitMQ` isn't defined; 3806)
[2024-11-10T12:54:34.804+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-10T12:54:34.824+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
