[2024-11-10T12:59:12.115+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T12:59:08.334482+00:00 [queued]>
[2024-11-10T12:59:12.121+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T12:59:08.334482+00:00 [queued]>
[2024-11-10T12:59:12.122+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-10T12:59:12.132+0000] {taskinstance.py:2217} INFO - Executing <Task(RabbitMQSensor): trip_stop_sensor> on 2024-11-10 12:59:08.334482+00:00
[2024-11-10T12:59:12.137+0000] {standard_task_runner.py:60} INFO - Started process 4244 to run task
[2024-11-10T12:59:12.139+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'analytics_pipeline', 'trip_stop_sensor', 'scheduled__2024-11-10T12:59:08.334482+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/analytics_pipeline.py', '--cfg-path', '/tmp/tmp9ebwxmzu']
[2024-11-10T12:59:12.141+0000] {standard_task_runner.py:88} INFO - Job 277: Subtask trip_stop_sensor
[2024-11-10T12:59:12.176+0000] {task_command.py:423} INFO - Running <TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T12:59:08.334482+00:00 [running]> on host 2a2d16a2b1e8
[2024-11-10T12:59:12.233+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='analytics_pipeline' AIRFLOW_CTX_TASK_ID='trip_stop_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T12:59:08.334482+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-10T12:59:08.334482+00:00'
[2024-11-10T12:59:12.246+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/sensors/rabbitmq.py", line 32, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/sensors/rabbitmq.py", line 37, in poke
    message = hook.pull(self.queue_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 123, in pull
    connection = self.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 48, in get_conn
    conn = self.get_connection(self.rabbitmq_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `RabbitMQ` isn't defined
[2024-11-10T12:59:12.248+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=analytics_pipeline, task_id=trip_stop_sensor, execution_date=20241110T125908, start_date=20241110T125912, end_date=20241110T125912
[2024-11-10T12:59:12.257+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 277 for task trip_stop_sensor (The conn_id `RabbitMQ` isn't defined; 4244)
[2024-11-10T12:59:12.272+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-10T12:59:12.292+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
