[2024-11-10T20:29:05.126+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: analytics_pipeline.get_dates_for_trip manual__2024-11-10T18:48:51.050554+00:00 [queued]>
[2024-11-10T20:29:05.134+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: analytics_pipeline.get_dates_for_trip manual__2024-11-10T18:48:51.050554+00:00 [queued]>
[2024-11-10T20:29:05.135+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-10T20:29:05.145+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): get_dates_for_trip> on 2024-11-10 18:48:51.050554+00:00
[2024-11-10T20:29:05.149+0000] {standard_task_runner.py:60} INFO - Started process 944 to run task
[2024-11-10T20:29:05.152+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'analytics_pipeline', 'get_dates_for_trip', 'manual__2024-11-10T18:48:51.050554+00:00', '--job-id', '1262', '--raw', '--subdir', 'DAGS_FOLDER/analytics_pipeline.py', '--cfg-path', '/tmp/tmpvgfsvb7t']
[2024-11-10T20:29:05.153+0000] {standard_task_runner.py:88} INFO - Job 1262: Subtask get_dates_for_trip
[2024-11-10T20:29:05.186+0000] {task_command.py:423} INFO - Running <TaskInstance: analytics_pipeline.get_dates_for_trip manual__2024-11-10T18:48:51.050554+00:00 [running]> on host 2a2d16a2b1e8
[2024-11-10T20:29:05.243+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='analytics_pipeline' AIRFLOW_CTX_TASK_ID='get_dates_for_trip' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T18:48:51.050554+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T18:48:51.050554+00:00'
[2024-11-10T20:29:05.250+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/get_dates_for_trip.py", line 47, in get_dates_for_trip
    trip_stop_message = json.loads(kwargs['task_instance'].xcom_pull(task_ids='trip_stop_sensor'))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
[2024-11-10T20:29:05.260+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=analytics_pipeline, task_id=get_dates_for_trip, execution_date=20241110T184851, start_date=20241110T202905, end_date=20241110T202905
[2024-11-10T20:29:05.268+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1262 for task get_dates_for_trip (Expecting property name enclosed in double quotes: line 1 column 2 (char 1); 944)
[2024-11-10T20:29:05.284+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-10T20:29:05.295+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
