[2024-11-10T12:59:55.722+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T12:59:52.443855+00:00 [queued]>
[2024-11-10T12:59:55.728+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T12:59:52.443855+00:00 [queued]>
[2024-11-10T12:59:55.729+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-10T12:59:55.738+0000] {taskinstance.py:2217} INFO - Executing <Task(RabbitMQSensor): trip_stop_sensor> on 2024-11-10 12:59:52.443855+00:00
[2024-11-10T12:59:55.743+0000] {standard_task_runner.py:60} INFO - Started process 4318 to run task
[2024-11-10T12:59:55.745+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'analytics_pipeline', 'trip_stop_sensor', 'scheduled__2024-11-10T12:59:52.443855+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/analytics_pipeline.py', '--cfg-path', '/tmp/tmpgqu8nymm']
[2024-11-10T12:59:55.747+0000] {standard_task_runner.py:88} INFO - Job 299: Subtask trip_stop_sensor
[2024-11-10T12:59:55.781+0000] {task_command.py:423} INFO - Running <TaskInstance: analytics_pipeline.trip_stop_sensor scheduled__2024-11-10T12:59:52.443855+00:00 [running]> on host 2a2d16a2b1e8
[2024-11-10T12:59:55.844+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='analytics_pipeline' AIRFLOW_CTX_TASK_ID='trip_stop_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T12:59:52.443855+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-10T12:59:52.443855+00:00'
[2024-11-10T12:59:55.851+0000] {base.py:83} INFO - Using connection ID 'RabbitMQ' for task execution.
[2024-11-10T12:59:55.852+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pika/connection.py", line 389, in port
    self._port = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/sensors/rabbitmq.py", line 32, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/sensors/rabbitmq.py", line 37, in poke
    message = hook.pull(self.queue_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 123, in pull
    connection = self.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 53, in get_conn
    parameters = pika.ConnectionParameters(
  File "/home/airflow/.local/lib/python3.8/site-packages/pika/connection.py", line 645, in __init__
    self.port = port
  File "/home/airflow/.local/lib/python3.8/site-packages/pika/connection.py", line 391, in port
    raise TypeError('port must be an int, but got %r' % (value,))
TypeError: port must be an int, but got None
[2024-11-10T12:59:55.858+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=analytics_pipeline, task_id=trip_stop_sensor, execution_date=20241110T125952, start_date=20241110T125955, end_date=20241110T125955
[2024-11-10T12:59:55.867+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 299 for task trip_stop_sensor (port must be an int, but got None; 4318)
[2024-11-10T12:59:55.877+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-10T12:59:55.897+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
